[package]
name = "advent-of-rust-2023"
version = "0.1.0"
edition = "2021"

[profile.release]
opt-level = 3
codegen-units = 1
lto = true

[dependencies]
itertools = "0.12.0"
rayon = "1.8.0"
regex = "1.10.2"
